plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
title: "ABDevSpace -- Your Guide to IT"
description: "Welcome to ABDevSpace — your go-to place for learning Java, exploring IT concepts, and staying on top of the latest tech trends. Find easy-to-follow guides, helpful tutorials, and insights to help you grow on your tech journey."
